### ISSUE TITLE
PackageNotFoundError: Dlib

### ISSUE THREAD

**Issue by Tejeshwarabm** [menpo/conda-dlib#13]
I have followed all the steps mentioned below, 
$ conda install conda-build
$ git clone https://github.com/menpo/conda-dlib
$ cd conda-dlib
$ conda config --add channels menpo
$ conda build conda/
$ conda install /PATH/TO/DLIB/PACKAGE.tar.gz

##########################################
But I have faced following error

## PackageNotFoundError: Package missing in current linux-64 channels: 
  - dlib-19.4.0.tar.gz

**Comment by patricksnape** [comment]
Please use the conda-forge build of dlib `conda install dlib -c conda-forge`
