### ISSUE TITLE
Install on Windows

### ISSUE THREAD

**Issue by frankbreetz** [menpo/conda-dlib#15]
Hello,
I am trying to get this installed on windows and i am having an issue. Could you help? 

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3>conda install conda-build
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\ProgramData\Anaconda3:

The following packages will be UPDATED:

    conda:       4.3.30-py36h7e176b0_0 --> 4.3.31-py36_0
    conda-build: 3.0.27-py36h309a530_0 --> 3.1.6-py36_0

Proceed ([y]/n)? y

conda-4.3.31-p 100% |###############################| Time: 0:00:00   3.36 MB/s
conda-build-3. 100% |###############################| Time: 0:00:00   5.46 MB/s

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3>git clone https://github.com/menpo/conda-dlib
Cloning into 'conda-dlib'...
remote: Counting objects: 301, done.
Receiving objects: 100% (301/301), 976.45 KiB | 0 bytes/s, done.

Resolving deltas: 100% (174/174), done.
Checking connectivity... done.

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3>cd conda-dlib

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-dlib>conda config --add channels menpo

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-dlib>conda build conda/
Attempting to finalize metadata for dlib
INFO:conda_build.metadata:Attempting to finalize metadata for dlib
BUILD START: ['dlib-19.4-py36_0.tar.bz2']

The following NEW packages will be INSTALLED:

    boost:          1.59.0-py36_0            menpo
    bzip2:          1.0.6-haa5b126_2
    certifi:        2017.11.5-py36hb8ac631_0
    cmake:          3.9.4-h4b83b1b_0
    icc_rt:         2017.0.4-h97af966_0
    intel-openmp:   2018.0.0-hd92c6cd_8
    libpng:         1.6.32-h140d38e_4
    mkl:            2018.0.1-h2108138_4
    numpy:          1.11.3-py36hb60be0b_3
    pip:            9.0.1-py36h226ae91_4
    python:         3.6.3-h3b118a2_4
    setuptools:     36.5.0-py36h65f9e6e_0
    vc:             14-h2379b0c_2
    vs2015_runtime: 14.0.25123-hd4c4e62_2
    wheel:          0.30.0-py36h6c3ec14_1
    wincertstore:   0.2-py36h7fe50ca_0
    zlib:           1.2.11-h8395fce_2

Source cache directory is: C:\ProgramData\Anaconda3\conda-bld\src_cache
Downloading source to cache: v19.4_2bed9669f1.tar.gz
Downloading https://github.com/davisking/dlib/archive/v19.4.tar.gz
Success
Extracting download
Applying patch: 'C:\\ProgramData\\Anaconda3\\conda-dlib\\conda\\win_boost.patch'
        Error:
            Cannot use 'git' (not a git repo and/or patch) and did not find 'patch' in: C:\ProgramData\Anaconda3\conda-bld\dlib_1513781840234\_h_env\Scripts;C:\ProgramData\Anaconda3\conda-bld\dlib_1513781840234\_h_env\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\conda-bld\dlib_1513781840234\_h_env\Library\usr\bin;C:\ProgramData\Anaconda3\conda-bld\dlib_1513781840234\_h_env\Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\conda-bld\dlib_1513781840234\_h_env;C:\ProgramData\Anaconda3\conda-bld\dlib_1513781840234\_h_env\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\conda-bld\dlib_1513781840234\_h_env\Library\usr\bin;;C:\ProgramData\Anaconda3\conda-bld\dlib_1513781840234\_h_env\Library\bin;C:\ProgramData\Anaconda3\conda-bld\dlib_1513781840234\_h_env\Scripts;C:\ProgramData\Anaconda3\conda-bld\dlib_1513781840234\_h_env\Scripts;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\Win64;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Embarcadero\Studio\18.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\18.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl\Win64;C:\Program Files (x86)\CollabNet\Subversion Client;C:\Windows\Microsoft.NET\Framework\v1.1.4322\;C:\Program Files (x86)\Borland\BDS\4.0\Bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Common Files\SigmaTEK Shared\RealDWGFonts;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Microsoft\Web Platform Installer\;C:\Users\frank.breetz\Documents\Borland Studio Projects\Bpl;C:\Users\frank.breetz\AppData\Roaming\Boxstarter;C:\Users\frank.breetz\AppData\Local\Code\bin
            You can install 'patch' using apt-get, yum (Linux), Xcode (MacOSX),
            or conda, m2-patch (Windows),

**Comment by patricksnape** [comment]
Please just install using conda-forge ‘conda install -c conda-forge dlib’

I’m afraid I can’t give support for windows as it’s way too complicated to set up a windows build system for python.

**Comment by frankbreetz** [comment]
Thanks, that looked like it worked
